### ISSUE TITLE
Unexpected token error

### ISSUE THREAD

**Issue by MrFirthy** [alpacaaa/react-native-media-queries#1]
Apologies in advance if I've implemented this incorrectly, but I keep getting the following error when trying to use this:

`node_modules/react-native-media-queries/index.js: Unexpected token (25:8)`

Below is the code I've been trying to use, which mirrors the example in the README bar the rule itself:

```
const base = {
  offset: {
    marginLeft: 50
  }
};

const mediaStyles = createStyles(
  base,

  maxHeight(500, {
       offset: {
          marginLeft: 0
       }
   })
);
```

I then try to use the rule `mediaStyles.offset`

Any help on this would be really appreciated.

**Comment by alpacaaa** [comment]
Hi, your code looks correct, would you mind posting the entire file? Also, what version of React Native are you using?

**Comment by MrFirthy** [comment]
Sure. My version of React Native is `^0.22.2` and a simple version of the code is:

```
render() {
        const baseStyles = {
            balanceOffset: {
                marginLeft: 50
            }
        };

        const mediaStyles = createStyles(
            baseStyles,

            maxHeight(500, {
                balanceOffset: {
                    marginLeft: 0
                }
            })
        );

      return (
         <ScrollView>
                <View style={styles.whiteBox}>
                        <Text style={styles.balanceTitle}>Your account balance</Text>
                        <View style={mediaStyles.balanceOffset}>
                            <Text style={[styles.balanceAmount, styles.green]}>£XX.XX</Text>
                        </View>
                </View>
         </ScrollView>
      )
}
```

The references to `styles.` are other styles held in another file and brought in through props.

```
Dashboard.propTypes = {
    styles: React.PropTypes.object.isRequired
    ...
}
```

**Comment by alpacaaa** [comment]
Mmh as a general rule you shouldn't use `createStyles` in the render method. Aside from that, judging from the error maybe it's a problem with Babel not compiling the file correctly? Did you install any additional Babel presets or plugins? It would really help to have a fully reproducible example.

**Comment by raz21** [comment]
I  am also getting same error

ERROR in ./~/react-native-media-queries/index.js
Module parse failed: ~\node_modules\react-native-media-queries\index.js Unexpected token (23:8)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (23:8)

Can we get any example project and Webconfig for itz Babel presets or plugins?? Please help us.

here is my code:

'use strict';
var React = require('react-native');
import { createStyles, maxWidth, minWidth } from 'react-native-media-queries';
var React, {
  Text,
  View,
  Component,
} = React;

var ComponentOne = React.createClass({
    render: function() {
    return (

```
        <View style={styles.content}>                                  
            <Text  style={styles.lbl1}> Please enter or create room ID </Text>
        </View>
)
```

  }
})

const base = {
    content:{  
    flex: 1,  
    flexDirection: 'column', 
    backgroundColor: '#ebebeb',
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf : 'stretch',
    },
};

const styles = createStyles(
  base,
  minWidth(769, maxWidth(2300, {
    content:{ 
    flex: 1,  
    flexDirection: 'column', 
    backgroundColor: '#f4f3f3',
    alignItems: 'center',
    justifyContent: 'center',
        textAlign:'center',
    alignSelf : 'stretch',
    margin:100, 
    borderRadius: 10,
    borderColor: '#ffffff',
    borderWidth: 3,
        },  
  }))
);
module.exports = ComponentOne;

**Comment by alpacaaa** [comment]
Thanks for the snippet, next release will be compiled so that babel won't complain. I'll update this thread shortly.

**Comment by alpacaaa** [comment]
I just released a new version which should fix the problem you were seeing. Would you mind giving it a try by reinstalling this module?

Pinging @MrFirthy @raz21

**Comment by MrFirthy** [comment]
@alpacaaa Yep that seems to be working correctly for me now. Thanks for the update :+1:

**Comment by alpacaaa** [comment]
@MrFirthy cool! Closing this.
